# fly.toml app configuration file generated for 2024-fullstack-osa13 on 2024-07-30T11:05:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2024-fullstack-osa13'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
